#
###################################
# Site wide configuration
####################################
#
title: Jumprope Design Blog
email: info@jumprope.design
description: A simple and awesome blog for Jumprope Design.
url: https://jumprope-design.github.io/


#
###################################
# Jekyll configuration
####################################
#
timezone:          Chicago
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Jumprope Design
  avatar: jumprope-logo.png
  job: "Web Application Design and Development."
  bio: "Jumprope Design is a boutique web development company that designs and develops simple, modern websites and web applications."
  email: "info@jumprope.design"
  disqus-shortname:
  twitter: "@jumprope_design"
  facebook: "jumprope.design"
  google:
    plus: #username
    analytics: UA-98880023-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: jumprope-design
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: jumprope.design
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
